### PR TITLE
Fix some styling issues

### PR DESCRIPTION
**Pull request by RomRider**

### CODE REVIEW

**Comment by ofekashery** [comment]
Hey @RomRider, thanks for contributing 🚀
Can you explain why this is necessary?

**Comment by RomRider** [comment]
Sure.
That's without `display: block`:
image

That's with display block:
image

And the configuration (using decluttering-card, thus the `[[xxxx]]`):
```yaml
    type: custom:vertical-stack-in-card
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            size: '[[size]]'
            entity: '[[entity]]'
            template: cover_up
          - type: custom:button-card
            size: '[[size]]'
            entity: '[[entity]]'
            template: cover_stop
          - type: custom:button-card
            size: '[[size]]'
            entity: '[[entity]]'
            template: cover_down
      - type: custom:card-modder
        extra_styles: >
          .card-content {
            padding: 0px 0px
          }
        card:
          type: entities
          entities:
            - type: custom:slider-entity-row
              entity: '[[entity]]'
              full_row: true
              hide_state: true
      - type: custom:button-card
        name: '[[name]]'
        template: cover_name
```

**Comment by ofekashery** [comment]
Thanks, merged

**Comment by RomRider** [comment]
Thanks a lot!
Is there any way that you could release a version with this PR so that `custom_updater` and `hacs` could pick it up? :)

**Pull request merged**
